---
output:
  html_document:
    keep_md: true
---

  I come across some good pieces of advice for PhD students that I feel urged to share. They are for graduate students in economics but since finance students share similar coursework in the first year, so I think the advice applies.

1. **First-year general advice**: [Mastering Year One](https://static1.squarespace.com/static/5adc9e5325bf0289a67f02b4/t/5adcb2f9758d46f994d0e795/1524413186131/MY1.pdf) by Alex Zentefis. He also shares a book list for graduate school in economics or finance.

2. **Data Management and Coding**: [Code and Data for the Social Sciences: A Practitioner’s Guide](https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf) by Matthew Gentzkow and Jesse M. Shapiro. This is a good guide for empiricists.
    * Sources to start learning Git, GitHub, and connecting them with your preferred programming languages: [R language](https://happygitwithr.com); [Julia language](https://lectures.quantecon.org/jl/more_julia/version_control.html). I strongly recommend to learn at least one version control system (_git_ in this case). It will improve your workflow significantly. 
    * A good text editor to focus on writing codes: [Sublime Text](https://lectures.quantecon.org/jl/more_julia/version_control.html); [Send Sublime Text codes to R](https://www.r-bloggers.com/sublime-text-3-an-alternative-to-rstudio/)
    * If you don't want to install the programming languages, their IDEs (e.g. RStudio for R, Spyder for Python), and their basic packages, consider [Anaconda](https://www.anaconda.com). It is a platform to work on coding with your chosen programming languages (Python/R/Julia or all). They integrate the languages IDEs with many installed packages.
    
